const tracery = require('tracery-grammar');

const grammar = tracery.createGrammar({
  gijinkaNouns: require('./nouns'),
  characterType: [
    'anime girl',
    'anime girl',
    'anime girl',
    'anime girl',
    'loli',
    'chibi girl',
  ],
  gijinkaCharacterType: ['gijinka of "#gijinkaNouns#"'],
  color: [
    'silver',
    'dark brown',
    'medium brown',
    'light brown',
    'golden',
    'red',
    'orange',
    'rose gold',
    'light pink',
    'dark pink',
    'peach',
    'dark green',
    'emerald',
    'neon green',
    'mint green',
    'teal',
    'indigo',
    'light blue',
    'midnight blue',
    'lilac',
    'plum',
    'lavender',
    'violet',
    'rainbow',
    'purple',
    'white',
    'green',
  ],
  hairLength: ['short', 'medium', 'long', 'very long', 'crazy protagonist'],
  hairColor: [
    'vanilla',
    'honey',
    'caramel',
    'cinnamon',
    'blue black',
    'black',
    'chocolate',
    'dark blonde',
    'medium blonde',
    'light blonde',
    'very light blonde',
    '#color#',
  ],
  clothingType: [
    'fantasy outfit',
    'fantasy armor',
    'casual outfit',
    'school uniform',
    'fantasy school uniform',
    'sports uniform',
    'military uniform',
    'dress',
    'modern outfit',
    'multicolored outfit',
    'animal suit',
    'formal outfit',
    'sexy outfit',
    'swimsuit',
    'cosplay',
    'futuristic outfit',
    'cyberpunk outfit',
    'steampunk outfit',
    'princess dress',
    'adventurer outfit',
    'MMORPG healer outfit',
    'MMORPG tank armor',
  ],
  clothingAccessoriesNoA: [
    'glasses',
    'horns',
    'earrings',
    'funny shoes',
    'wings',
  ],
  clothingAccessories: [
    'skirt',
    'hat',
    'beanie',
    'party hat',
    'eyepatch',
    'necklace',
    'watch',
    'bracelet',
    'phone',
    'fantasy weapon',
    'book',
    'bag or backpack',
    'tail',
    'tail',
    'pet',
    'halo',
  ],
  emotion: [
    'sad',
    'crying',
    'sobbing',
    'happy',
    'happy',
    'happy',
    'smiling',
    'smiling',
    'smiling',
    'laughing',
    'laughing',
    'laughing',
    'excited',
    'excited',
    'excited',
    'mesmerized',
    'curious',
    'confused',
    'angry',
    'furious',
    'distraught',
    'speechless',
    'sulking',
    'thinking',
    'worried',
    'embarrassed',
    'shy',
    'blushing',
    'focused',
    'desperate',
    'energetic',
    'determined',
    'motivated',
    'confident',
    'distracted',
    'smug',
    'hungry',
    'pouting',
    'yawning',
    'sleepy',
    'showing a neutral expression',
    'showing a neutral expression',
  ],
  action: [
    'having an idea',
    'in love',
    'staring at you',
    'jumping',
    'falling',
    'flying',
    'running',
    'sitting',
    'lying down',
    'showing a neutral expression',
    'staring at the distance',
    'staring at the distance',,
    'waving',
    'walking',
    'reading',
    'drawing',
    'listening to music',
    'using a computer',
    'using a laptop'
  ],
  characterEmotionOrAction: [
    '#emotion#',
    '#emotion#',
    '#emotion#',
    '#emotion#',
    '#action#',
  ],
  backgroundType: ['flat', 'abstract or flat', 'indoors', 'outdoors', 'nature'],

  characterDescription: [
    '#characterType.a# with #hairLength# #hairColor# hair, dressed in #clothingType.a# with #clothingAccessories.a# that is #characterEmotionOrAction#',
    '#characterType.a# with #hairLength# #hairColor# hair, dressed in #clothingType.a# with #clothingAccessories.a# that is #characterEmotionOrAction#',
    '#characterType.a# with #hairLength# #hairColor# hair, dressed in #clothingType.a# with #clothingAccessories.a# that is #characterEmotionOrAction#',
    '#characterType.a# with #hairLength# #hairColor# hair, dressed in #clothingType.a# with #clothingAccessoriesNoA# that is #characterEmotionOrAction#',
    '#characterType.a# with #hairLength# #hairColor# hair, dressed in #clothingType.a# and is #characterEmotionOrAction#',
    '#gijinkaCharacterType.a# with #hairLength# #hairColor# hair that is #characterEmotionOrAction#',
  ],
  backgroundDescription: ['#backgroundType#'],

  // prompts
  animeCharacter: [
    'Draw #characterDescription#. For the background make it #backgroundDescription#.',
    'Draw #characterDescription#. For the background make it #backgroundDescription#.',
    'Draw #characterDescription#. For the background make it #backgroundDescription#.',
    'Draw some fanart of a character you like, they must be #characterEmotionOrAction# and in a #backgroundDescription# background.',
    'Draw some fanart of a character from an anime you like, they must be #characterEmotionOrAction# and in a #backgroundDescription# background.',
    'Draw some fanart of a character from a game you like, they must be #characterEmotionOrAction# and in a #backgroundDescription# background.',
  ],
});

grammar.addModifiers(tracery.baseEngModifiers);

module.exports = () => grammar.flatten('#animeCharacter#');
